// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.27  $
// File generated on 2017/3/23 ¤U¤È 02:02:29 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Users\tony\Downloads\Skype4COM\Skype4COM.dll (1)
// LIBID: {03282B5D-B38F-469D-849A-09B0A7F4881B}
// LCID: 0
// Helpfile: C:\Program Files (x86)\Common Files\Skype\Skype4COM.chm
// HelpString: Skype4COM 1.0 Type Library.
// DepndLst: 
//   (1) v2.0 stdole, (C:\Windows\SysWOW64\stdole2.tlb)
// ************************************************************************ //
#ifndef   SKYPE4COMLib_OCXH
#define   SKYPE4COMLib_OCXH

#pragma option push -b -w-inl

#include <olectrls.hpp>
#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "SKYPE4COMLib_TLB.h"
namespace Skype4comlib_tlb
{

// *********************************************************************//
// HelpString: Skype4COM 1.0 Type Library.
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TSkype
// Help String      : Skype class.
// Default Interface: ISkype
// Def. Intf. Object: TCOMISkype
// Def. Intf. DISP? : No
// Event   Interface: _ISkypeEvents
// TypeFlags        : (2) CanCreate
// *********************************************************************//

// *********************************************************************//
// Definition of closures to allow VCL handlers to catch OCX events.      
// *********************************************************************//
typedef void __fastcall (__closure * TSkypeCommand)(System::TObject * Sender, 
                                                    Skype4comlib_tlb::ICommand* pCommand/*[in]*/);
typedef void __fastcall (__closure * TSkypeReply)(System::TObject * Sender, 
                                                  Skype4comlib_tlb::ICommand* pCommand/*[in]*/);
typedef void __fastcall (__closure * TSkypeError)(System::TObject * Sender, 
                                                  Skype4comlib_tlb::ICommand* pCommand/*[in]*/, 
                                                  long Number/*[in]*/, BSTR Description/*[in]*/);
typedef void __fastcall (__closure * TSkypeAttachmentStatus)(System::TObject * Sender, 
                                                             Skype4comlib_tlb::TAttachmentStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeConnectionStatus)(System::TObject * Sender, 
                                                             Skype4comlib_tlb::TConnectionStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeUserStatus)(System::TObject * Sender, 
                                                       Skype4comlib_tlb::TUserStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeOnlineStatus)(System::TObject * Sender, 
                                                         Skype4comlib_tlb::IUser* pUser/*[in]*/, 
                                                         Skype4comlib_tlb::TOnlineStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeCallStatus)(System::TObject * Sender, 
                                                       Skype4comlib_tlb::ICall* pCall/*[in]*/, 
                                                       Skype4comlib_tlb::TCallStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeMute)(System::TObject * Sender, 
                                                 VARIANT_BOOL Mute/*[in]*/);
typedef void __fastcall (__closure * TSkypeMessageStatus)(System::TObject * Sender, 
                                                          Skype4comlib_tlb::IChatMessage* pMessage/*[in]*/, 
                                                          Skype4comlib_tlb::TChatMessageStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeMessageHistory)(System::TObject * Sender, 
                                                           BSTR Username/*[in]*/);
typedef void __fastcall (__closure * TSkypeAutoAway)(System::TObject * Sender, 
                                                     VARIANT_BOOL Automatic/*[in]*/);
typedef void __fastcall (__closure * TSkypeCallDtmfReceived)(System::TObject * Sender, 
                                                             Skype4comlib_tlb::ICall* pCall/*[in]*/, 
                                                             BSTR code/*[in]*/);
typedef void __fastcall (__closure * TSkypeVoicemailStatus)(System::TObject * Sender, 
                                                            Skype4comlib_tlb::IVoicemail* pMail/*[in]*/, 
                                                            Skype4comlib_tlb::TVoicemailStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeApplicationConnecting)(System::TObject * Sender, 
                                                                  Skype4comlib_tlb::IApplication* pApp/*[in]*/, 
                                                                  Skype4comlib_tlb::IUserCollection* pUsers/*[in]*/);
typedef void __fastcall (__closure * TSkypeApplicationStreams)(System::TObject * Sender, 
                                                               Skype4comlib_tlb::IApplication* pApp/*[in]*/, 
                                                               Skype4comlib_tlb::IApplicationStreamCollection* pStreams/*[in]*/);
typedef void __fastcall (__closure * TSkypeApplicationDatagram)(System::TObject * Sender, 
                                                                Skype4comlib_tlb::IApplication* pApp/*[in]*/, 
                                                                Skype4comlib_tlb::IApplicationStream* pStream/*[in]*/, 
                                                                BSTR Text/*[in]*/);
typedef void __fastcall (__closure * TSkypeApplicationSending)(System::TObject * Sender, 
                                                               Skype4comlib_tlb::IApplication* pApp/*[in]*/, 
                                                               Skype4comlib_tlb::IApplicationStreamCollection* pStreams/*[in]*/);
typedef void __fastcall (__closure * TSkypeApplicationReceiving)(System::TObject * Sender, 
                                                                 Skype4comlib_tlb::IApplication* pApp/*[in]*/, 
                                                                 Skype4comlib_tlb::IApplicationStreamCollection* pStreams/*[in]*/);
typedef void __fastcall (__closure * TSkypeContactsFocused)(System::TObject * Sender, 
                                                            BSTR Username/*[in]*/);
typedef void __fastcall (__closure * TSkypeGroupVisible)(System::TObject * Sender, 
                                                         Skype4comlib_tlb::IGroup* pGroup/*[in]*/, 
                                                         VARIANT_BOOL Visible/*[in]*/);
typedef void __fastcall (__closure * TSkypeGroupExpanded)(System::TObject * Sender, 
                                                          Skype4comlib_tlb::IGroup* pGroup/*[in]*/, 
                                                          VARIANT_BOOL Expanded/*[in]*/);
typedef void __fastcall (__closure * TSkypeGroupUsers)(System::TObject * Sender, 
                                                       Skype4comlib_tlb::IGroup* pGroup/*[in]*/, 
                                                       Skype4comlib_tlb::IUserCollection* pUsers/*[in]*/);
typedef void __fastcall (__closure * TSkypeGroupDeleted)(System::TObject * Sender, 
                                                         long GroupId/*[in]*/);
typedef void __fastcall (__closure * TSkypeUserMood)(System::TObject * Sender, 
                                                     Skype4comlib_tlb::IUser* pUser/*[in]*/, 
                                                     BSTR MoodText/*[in]*/);
typedef void __fastcall (__closure * TSkypeSmsMessageStatusChanged)(System::TObject * Sender, 
                                                                    Skype4comlib_tlb::ISmsMessage* pMessage/*[in]*/, 
                                                                    Skype4comlib_tlb::TSmsMessageStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeSmsTargetStatusChanged)(System::TObject * Sender, 
                                                                   Skype4comlib_tlb::ISmsTarget* pTarget/*[in]*/, 
                                                                   Skype4comlib_tlb::TSmsTargetStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeCallInputStatusChanged)(System::TObject * Sender, 
                                                                   Skype4comlib_tlb::ICall* pCall/*[in]*/, 
                                                                   VARIANT_BOOL Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeAsyncSearchUsersFinished)(System::TObject * Sender, 
                                                                     long Cookie/*[in]*/, 
                                                                     Skype4comlib_tlb::IUserCollection* pUsers/*[in]*/);
typedef void __fastcall (__closure * TSkypeCallSeenStatusChanged)(System::TObject * Sender, 
                                                                  Skype4comlib_tlb::ICall* pCall/*[in]*/, 
                                                                  VARIANT_BOOL Status);
typedef void __fastcall (__closure * TSkypePluginEventClicked)(System::TObject * Sender, 
                                                               Skype4comlib_tlb::IPluginEvent* pEvent/*[in]*/);
typedef void __fastcall (__closure * TSkypePluginMenuItemClicked)(System::TObject * Sender, 
                                                                  Skype4comlib_tlb::IPluginMenuItem* pMenuItem/*[in]*/, 
                                                                  Skype4comlib_tlb::IUserCollection* pUsers/*[in]*/, 
                                                                  Skype4comlib_tlb::TPluginContext PluginContext/*[in]*/, 
                                                                  BSTR ContextId/*[in]*/);
typedef void __fastcall (__closure * TSkypeWallpaperChanged)(System::TObject * Sender, 
                                                             BSTR Path/*[in]*/);
typedef void __fastcall (__closure * TSkypeFileTransferStatusChanged)(System::TObject * Sender, 
                                                                      Skype4comlib_tlb::IFileTransfer* pTransfer/*[in]*/, 
                                                                      Skype4comlib_tlb::TFileTransferStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeCallTransferStatusChanged)(System::TObject * Sender, 
                                                                      Skype4comlib_tlb::ICall* pCall/*[in]*/, 
                                                                      Skype4comlib_tlb::TCallStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeChatMembersChanged)(System::TObject * Sender, 
                                                               Skype4comlib_tlb::IChat* pChat/*[in]*/, 
                                                               Skype4comlib_tlb::IUserCollection* pMembers/*[in]*/);
typedef void __fastcall (__closure * TSkypeChatMemberRoleChanged)(System::TObject * Sender, 
                                                                  Skype4comlib_tlb::IChatMember* pMember/*[in]*/, 
                                                                  Skype4comlib_tlb::TChatMemberRole Role/*[in]*/);
typedef void __fastcall (__closure * TSkypeCallVideoStatusChanged)(System::TObject * Sender, 
                                                                   Skype4comlib_tlb::ICall* pCall/*[in]*/, 
                                                                   Skype4comlib_tlb::TCallVideoStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeCallVideoSendStatusChanged)(System::TObject * Sender, 
                                                                       Skype4comlib_tlb::ICall* pCall/*[in]*/, 
                                                                       Skype4comlib_tlb::TCallVideoSendStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeCallVideoReceiveStatusChanged)(System::TObject * Sender, 
                                                                          Skype4comlib_tlb::ICall* pCall/*[in]*/, 
                                                                          Skype4comlib_tlb::TCallVideoSendStatus Status/*[in]*/);
typedef void __fastcall (__closure * TSkypeSilentModeStatusChanged)(System::TObject * Sender, 
                                                                    VARIANT_BOOL Silent/*[in]*/);
typedef void __fastcall (__closure * TSkypeUILanguageChanged)(System::TObject * Sender, 
                                                              BSTR code/*[in]*/);
typedef void __fastcall (__closure * TSkypeUserAuthorizationRequestReceived)(System::TObject * Sender, 
                                                                             Skype4comlib_tlb::IUser* pUser/*[in]*/);
//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
// Proxy class to host Skype class. in CBuilder IDE/Applications.
//-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
class PACKAGE TSkype : public TOleControl
{
  OVERLOADED_PROP_METHODS;
  static TNoParam  OptParam;
  static GUID      DEF_CTL_INTF;

  // Instance of Closures to expose OCX Events as VCL ones
  //
  TSkypeCommand                  FOnCommand;
  TSkypeReply                    FOnReply;
  TSkypeError                    FOnError;
  TSkypeAttachmentStatus         FOnAttachmentStatus;
  TSkypeConnectionStatus         FOnConnectionStatus;
  TSkypeUserStatus               FOnUserStatus;
  TSkypeOnlineStatus             FOnOnlineStatus;
  TSkypeCallStatus               FOnCallStatus;
  TNotifyEvent                   FOnCallHistory;
  TSkypeMute                     FOnMute;
  TSkypeMessageStatus            FOnMessageStatus;
  TSkypeMessageHistory           FOnMessageHistory;
  TSkypeAutoAway                 FOnAutoAway;
  TSkypeCallDtmfReceived         FOnCallDtmfReceived;
  TSkypeVoicemailStatus          FOnVoicemailStatus;
  TSkypeApplicationConnecting    FOnApplicationConnecting;
  TSkypeApplicationStreams       FOnApplicationStreams;
  TSkypeApplicationDatagram      FOnApplicationDatagram;
  TSkypeApplicationSending       FOnApplicationSending;
  TSkypeApplicationReceiving     FOnApplicationReceiving;
  TSkypeContactsFocused          FOnContactsFocused;
  TSkypeGroupVisible             FOnGroupVisible;
  TSkypeGroupExpanded            FOnGroupExpanded;
  TSkypeGroupUsers               FOnGroupUsers;
  TSkypeGroupDeleted             FOnGroupDeleted;
  TSkypeUserMood                 FOnUserMood;
  TSkypeSmsMessageStatusChanged  FOnSmsMessageStatusChanged;
  TSkypeSmsTargetStatusChanged   FOnSmsTargetStatusChanged;
  TSkypeCallInputStatusChanged   FOnCallInputStatusChanged;
  TSkypeAsyncSearchUsersFinished FOnAsyncSearchUsersFinished;
  TSkypeCallSeenStatusChanged    FOnCallSeenStatusChanged;
  TSkypePluginEventClicked       FOnPluginEventClicked;
  TSkypePluginMenuItemClicked    FOnPluginMenuItemClicked;
  TSkypeWallpaperChanged         FOnWallpaperChanged;
  TSkypeFileTransferStatusChanged FOnFileTransferStatusChanged;
  TSkypeCallTransferStatusChanged FOnCallTransferStatusChanged;
  TSkypeChatMembersChanged       FOnChatMembersChanged;
  TSkypeChatMemberRoleChanged    FOnChatMemberRoleChanged;
  TSkypeCallVideoStatusChanged   FOnCallVideoStatusChanged;
  TSkypeCallVideoSendStatusChanged FOnCallVideoSendStatusChanged;
  TSkypeCallVideoReceiveStatusChanged FOnCallVideoReceiveStatusChanged;
  TSkypeSilentModeStatusChanged  FOnSilentModeStatusChanged;
  TSkypeUILanguageChanged        FOnUILanguageChanged;
  TSkypeUserAuthorizationRequestReceived FOnUserAuthorizationRequestReceived;

  // Default Interace of OCX
  //
  TCOMISkype m_OCXIntf;

  // VCL Property Getters/Setters which delegate to OCX
  //
  BSTR            __fastcall get_Property(BSTR ObjectType/*[in]*/, BSTR ObjectId/*[in]*/, 
                                          BSTR PropName/*[in]*/);
  void            __fastcall set_Property(BSTR ObjectType/*[in]*/, BSTR ObjectId/*[in]*/, 
                                          BSTR PropName/*[in]*/, BSTR pVal/*[in]*/);
  BSTR            __fastcall get_Variable(BSTR Name/*[in]*/);
  void            __fastcall set_Variable(BSTR Name/*[in]*/, BSTR pVal/*[in]*/);
  TOLEBOOL        __fastcall get_Privilege(BSTR Name/*[in]*/);
  Skype4comlib_tlb::IUserPtr __fastcall get_CurrentUser(void);
  Skype4comlib_tlb::IConversionPtr __fastcall get_Convert(void);
  Skype4comlib_tlb::IUserCollectionPtr __fastcall get_Friends(void);
  Skype4comlib_tlb::ICallCollectionPtr __fastcall get_Calls(BSTR Target/*[in,def,opt]*/);
  Skype4comlib_tlb::ICallCollectionPtr __fastcall get_ActiveCalls(void);
  Skype4comlib_tlb::ICallCollectionPtr __fastcall get_MissedCalls(void);
  Skype4comlib_tlb::IChatMessageCollectionPtr __fastcall get_Messages(BSTR Target/*[in,def,opt]*/);
  Skype4comlib_tlb::IChatMessageCollectionPtr __fastcall get_MissedMessages(void);
  Skype4comlib_tlb::IUserPtr __fastcall get_User(BSTR Username/*[in,def,opt]*/);
  Skype4comlib_tlb::IChatMessagePtr __fastcall get_Message(long Id/*[in,def,opt]*/);
  Skype4comlib_tlb::ICallPtr __fastcall get_Call(long Id/*[in,def,opt]*/);
  Skype4comlib_tlb::IChatCollectionPtr __fastcall get_Chats(void);
  Skype4comlib_tlb::IChatPtr __fastcall get_Chat(BSTR Name/*[in,def,opt]*/);
  Skype4comlib_tlb::IConferencePtr __fastcall get_Conference(long Id/*[in,def,opt]*/);
  Skype4comlib_tlb::IConferenceCollectionPtr __fastcall get_Conferences(void);
  BSTR            __fastcall get_Profile(BSTR Property/*[in]*/);
  void            __fastcall set_Profile(BSTR Property/*[in]*/, BSTR pVal/*[in]*/);
  Skype4comlib_tlb::IChatCollectionPtr __fastcall get_ActiveChats(void);
  Skype4comlib_tlb::IChatCollectionPtr __fastcall get_MissedChats(void);
  Skype4comlib_tlb::IChatCollectionPtr __fastcall get_RecentChats(void);
  Skype4comlib_tlb::IChatCollectionPtr __fastcall get_BookmarkedChats(void);
  Skype4comlib_tlb::IVoicemailCollectionPtr __fastcall get_Voicemails(void);
  Skype4comlib_tlb::IUserCollectionPtr __fastcall get_UsersWaitingAuthorization(void);
  Skype4comlib_tlb::IApplicationPtr __fastcall get_Application(BSTR Name/*[in]*/);
  Skype4comlib_tlb::IVoicemailPtr __fastcall get_Greeting(BSTR Username/*[in,def,opt]*/);
  Skype4comlib_tlb::IProfilePtr __fastcall get_CurrentUserProfile(void);
  Skype4comlib_tlb::IGroupCollectionPtr __fastcall get_Groups(void);
  Skype4comlib_tlb::IGroupCollectionPtr __fastcall get_CustomGroups(void);
  Skype4comlib_tlb::IGroupCollectionPtr __fastcall get_HardwiredGroups(void);
  Skype4comlib_tlb::ISettingsPtr __fastcall get_Settings(void);
  Skype4comlib_tlb::IClientPtr __fastcall get_Client(void);
  Skype4comlib_tlb::ICommandPtr __fastcall get_Command(long Id/*[in]*/, BSTR Command/*[in]*/, 
                                                       BSTR Reply/*[in,def,opt]*/, 
                                                       VARIANT_BOOL Block/*[in,def,opt]*/, 
                                                       long Timeout/*[in,def,opt]*/);
  Skype4comlib_tlb::IVoicemailPtr __fastcall get_Voicemail(long Id/*[in]*/);
  Skype4comlib_tlb::IVoicemailCollectionPtr __fastcall get_MissedVoicemails(void);
  TOLEBOOL        __fastcall get_ApiSecurityContextEnabled(Skype4comlib_tlb::TApiSecurityContext Context/*[in]*/);
  Skype4comlib_tlb::ISmsMessageCollectionPtr __fastcall get_Smss(void);
  Skype4comlib_tlb::ISmsMessageCollectionPtr __fastcall get_MissedSmss(void);
  Skype4comlib_tlb::IFileTransferCollectionPtr __fastcall get_FileTransfers(void);
  Skype4comlib_tlb::IFileTransferCollectionPtr __fastcall get_ActiveFileTransfers(void);
  Skype4comlib_tlb::IUserCollectionPtr __fastcall get_FocusedContacts(void);

  // Static variables used by all instances of OCX proxy
  //
  static int          EventDispIDs[44];
  static TControlData CControlData;
  static GUID         CTL_DEF_INTF;

  // Method providing access to interface as __property 
  //
  TCOMISkype __fastcall GetDefaultInterface();
  TCOMISkype __fastcall GetControlInterface()
  { return GetDefaultInterface(); }

protected:
  void     __fastcall CreateControl  ();
  void     __fastcall InitControlData();

public:
  virtual  __fastcall TSkype(TComponent* AOwner) : TOleControl(AOwner)
  {};
  virtual  __fastcall TSkype(HWND        Parent) : TOleControl(Parent)
  {};

  // OCX methods
  //
  Skype4comlib_tlb::IUserCollectionPtr __fastcall SearchForUsers(BSTR Target/*[in]*/);
  void            __fastcall Attach(long Protocol/*[in,def,opt]*/, VARIANT_BOOL Wait/*[in,def,opt]*/);
  Skype4comlib_tlb::ICallPtr __fastcall PlaceCall(BSTR Target/*[in]*/, BSTR Target2/*[in,def,opt]*/, 
                                                  BSTR Target3/*[in,def,opt]*/, 
                                                  BSTR Target4/*[in,def,opt]*/);
  Skype4comlib_tlb::IChatMessagePtr __fastcall SendMessage(BSTR Username/*[in]*/, BSTR Text/*[in]*/);
  void            __fastcall SendCommand(Skype4comlib_tlb::ICommand* pCommand/*[in]*/);
  void            __fastcall ChangeUserStatus(Skype4comlib_tlb::TUserStatus newVal/*[in]*/);
  Skype4comlib_tlb::IChatPtr __fastcall CreateChatWith(BSTR Username/*[in]*/);
  Skype4comlib_tlb::IChatPtr __fastcall CreateChatMultiple(Skype4comlib_tlb::IUserCollection* pMembers/*[in]*/);
  Skype4comlib_tlb::IVoicemailPtr __fastcall SendVoicemail(BSTR Username/*[in]*/);
  void            __fastcall ClearChatHistory(void);
  void            __fastcall ClearVoicemailHistory(void);
  void            __fastcall ClearCallHistory(BSTR Username/*[in,def,opt]*/, 
                                              Skype4comlib_tlb::TCallHistory Type/*[in,def,opt]*/);
  void            __fastcall ResetCache(void);
  Skype4comlib_tlb::IGroupPtr __fastcall CreateGroup(BSTR GroupName/*[in]*/);
  void            __fastcall DeleteGroup(long GroupId/*[in]*/);
  void            __fastcall EnableApiSecurityContext(Skype4comlib_tlb::TApiSecurityContext Context/*[in]*/);
  Skype4comlib_tlb::ISmsMessagePtr __fastcall CreateSms(Skype4comlib_tlb::TSmsMessageType MessageType/*[in]*/, 
                                                        BSTR TargetNumbers/*[in]*/);
  Skype4comlib_tlb::ISmsMessagePtr __fastcall SendSms(BSTR TargetNumbers/*[in]*/, 
                                                      BSTR MessageText/*[in]*/, 
                                                      BSTR ReplyToNumber/*[in,def,opt]*/);
  long            __fastcall AsyncSearchUsers(BSTR Target/*[in]*/);
  Skype4comlib_tlb::IChatPtr __fastcall FindChatUsingBlob(BSTR Blob/*[in]*/);
  Skype4comlib_tlb::IChatPtr __fastcall CreateChatUsingBlob(BSTR Blob/*[in]*/);

  // OCX properties
  //
  __property BSTR Property[BSTR ObjectType][BSTR ObjectId][BSTR PropName]={ read=get_Property };
  __property BSTR Variable[BSTR Name]={ read=get_Variable };
  __property System::WideString CurrentUserHandle={ read=GetWideStringProp, index=4 };
  __property Activex::TOleEnum ConnectionStatus={ read=GetTOleEnumProp, index=6 };
  __property System::WideString Version={ read=GetWideStringProp, index=8 };
  __property TOLEBOOL Privilege[BSTR Name]={ read=get_Privilege };
  __property Skype4comlib_tlb::IUserPtr CurrentUser={ read=get_CurrentUser };
  __property Skype4comlib_tlb::IConversionPtr Convert={ read=get_Convert };
  __property Skype4comlib_tlb::IUserCollectionPtr Friends={ read=get_Friends };
  __property Skype4comlib_tlb::ICallCollectionPtr Calls[BSTR Target]={ read=get_Calls };
  __property Skype4comlib_tlb::ICallCollectionPtr ActiveCalls={ read=get_ActiveCalls };
  __property Skype4comlib_tlb::ICallCollectionPtr MissedCalls={ read=get_MissedCalls };
  __property Skype4comlib_tlb::IChatMessageCollectionPtr Messages[BSTR Target]={ read=get_Messages };
  __property Skype4comlib_tlb::IChatMessageCollectionPtr MissedMessages={ read=get_MissedMessages };
  __property Activex::TOleEnum AttachmentStatus={ read=GetTOleEnumProp, index=19 };
  __property Skype4comlib_tlb::IUserPtr User[BSTR Username]={ read=get_User };
  __property Skype4comlib_tlb::IChatMessagePtr Message[long Id]={ read=get_Message };
  __property Skype4comlib_tlb::ICallPtr Call[long Id]={ read=get_Call };
  __property Skype4comlib_tlb::IChatCollectionPtr Chats={ read=get_Chats };
  __property Skype4comlib_tlb::IChatPtr Chat[BSTR Name]={ read=get_Chat };
  __property Skype4comlib_tlb::IConferencePtr Conference[long Id]={ read=get_Conference };
  __property Skype4comlib_tlb::IConferenceCollectionPtr Conferences={ read=get_Conferences };
  __property BSTR Profile[BSTR Property]={ read=get_Profile };
  __property Skype4comlib_tlb::IChatCollectionPtr ActiveChats={ read=get_ActiveChats };
  __property Skype4comlib_tlb::IChatCollectionPtr MissedChats={ read=get_MissedChats };
  __property Skype4comlib_tlb::IChatCollectionPtr RecentChats={ read=get_RecentChats };
  __property Skype4comlib_tlb::IChatCollectionPtr BookmarkedChats={ read=get_BookmarkedChats };
  __property Skype4comlib_tlb::IVoicemailCollectionPtr Voicemails={ read=get_Voicemails };
  __property Skype4comlib_tlb::IUserCollectionPtr UsersWaitingAuthorization={ read=get_UsersWaitingAuthorization };
  __property Skype4comlib_tlb::IApplicationPtr Application[BSTR Name]={ read=get_Application };
  __property Skype4comlib_tlb::IVoicemailPtr Greeting[BSTR Username]={ read=get_Greeting };
  __property Skype4comlib_tlb::IProfilePtr CurrentUserProfile={ read=get_CurrentUserProfile };
  __property Skype4comlib_tlb::IGroupCollectionPtr Groups={ read=get_Groups };
  __property Skype4comlib_tlb::IGroupCollectionPtr CustomGroups={ read=get_CustomGroups };
  __property Skype4comlib_tlb::IGroupCollectionPtr HardwiredGroups={ read=get_HardwiredGroups };
  __property Skype4comlib_tlb::ISettingsPtr Settings={ read=get_Settings };
  __property Skype4comlib_tlb::IClientPtr Client={ read=get_Client };
  __property System::WideString FriendlyName={ write=SetWideStringProp, index=59 };
  __property Skype4comlib_tlb::ICommandPtr Command[long Id][BSTR Command][BSTR Reply][VARIANT_BOOL Block][long Timeout]={ read=get_Command };
  __property Skype4comlib_tlb::IVoicemailPtr Voicemail[long Id]={ read=get_Voicemail };
  __property Skype4comlib_tlb::IVoicemailCollectionPtr MissedVoicemails={ read=get_MissedVoicemails };
  __property TOLEBOOL ApiSecurityContextEnabled[Skype4comlib_tlb::TApiSecurityContext Context]={ read=get_ApiSecurityContextEnabled };
  __property Skype4comlib_tlb::ISmsMessageCollectionPtr Smss={ read=get_Smss };
  __property Skype4comlib_tlb::ISmsMessageCollectionPtr MissedSmss={ read=get_MissedSmss };
  __property System::WideString ApiWrapperVersion={ read=GetWideStringProp, index=70 };
  __property Skype4comlib_tlb::IFileTransferCollectionPtr FileTransfers={ read=get_FileTransfers };
  __property Skype4comlib_tlb::IFileTransferCollectionPtr ActiveFileTransfers={ read=get_ActiveFileTransfers };
  __property Skype4comlib_tlb::IUserCollectionPtr FocusedContacts={ read=get_FocusedContacts };
  __property System::WideString PredictiveDialerCountry={ read=GetWideStringProp, index=77 };
  __property TCOMISkype ControlInterface={ read=GetDefaultInterface };

  // Published properties
  //
__published:

  // Standard/Extended properties
  //

  // OCX properties
  //
  __property int Timeout={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=1 };
  __property Activex::TOleEnum CurrentUserStatus={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=5 };
  __property bool Mute={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=7 };
  __property int Protocol={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=20 };
  __property bool CommandId={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=46 };
  __property bool Cache={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=49 };
  __property bool SilentMode={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=71 };

  // OCX Events
  //
  __property TSkypeCommand OnCommand={ read=FOnCommand, write=FOnCommand };
  __property TSkypeReply OnReply={ read=FOnReply, write=FOnReply };
  __property TSkypeError OnError={ read=FOnError, write=FOnError };
  __property TSkypeAttachmentStatus OnAttachmentStatus={ read=FOnAttachmentStatus, write=FOnAttachmentStatus };
  __property TSkypeConnectionStatus OnConnectionStatus={ read=FOnConnectionStatus, write=FOnConnectionStatus };
  __property TSkypeUserStatus OnUserStatus={ read=FOnUserStatus, write=FOnUserStatus };
  __property TSkypeOnlineStatus OnOnlineStatus={ read=FOnOnlineStatus, write=FOnOnlineStatus };
  __property TSkypeCallStatus OnCallStatus={ read=FOnCallStatus, write=FOnCallStatus };
  __property TNotifyEvent OnCallHistory={ read=FOnCallHistory, write=FOnCallHistory };
  __property TSkypeMute OnMute={ read=FOnMute, write=FOnMute };
  __property TSkypeMessageStatus OnMessageStatus={ read=FOnMessageStatus, write=FOnMessageStatus };
  __property TSkypeMessageHistory OnMessageHistory={ read=FOnMessageHistory, write=FOnMessageHistory };
  __property TSkypeAutoAway OnAutoAway={ read=FOnAutoAway, write=FOnAutoAway };
  __property TSkypeCallDtmfReceived OnCallDtmfReceived={ read=FOnCallDtmfReceived, write=FOnCallDtmfReceived };
  __property TSkypeVoicemailStatus OnVoicemailStatus={ read=FOnVoicemailStatus, write=FOnVoicemailStatus };
  __property TSkypeApplicationConnecting OnApplicationConnecting={ read=FOnApplicationConnecting, write=FOnApplicationConnecting };
  __property TSkypeApplicationStreams OnApplicationStreams={ read=FOnApplicationStreams, write=FOnApplicationStreams };
  __property TSkypeApplicationDatagram OnApplicationDatagram={ read=FOnApplicationDatagram, write=FOnApplicationDatagram };
  __property TSkypeApplicationSending OnApplicationSending={ read=FOnApplicationSending, write=FOnApplicationSending };
  __property TSkypeApplicationReceiving OnApplicationReceiving={ read=FOnApplicationReceiving, write=FOnApplicationReceiving };
  __property TSkypeContactsFocused OnContactsFocused={ read=FOnContactsFocused, write=FOnContactsFocused };
  __property TSkypeGroupVisible OnGroupVisible={ read=FOnGroupVisible, write=FOnGroupVisible };
  __property TSkypeGroupExpanded OnGroupExpanded={ read=FOnGroupExpanded, write=FOnGroupExpanded };
  __property TSkypeGroupUsers OnGroupUsers={ read=FOnGroupUsers, write=FOnGroupUsers };
  __property TSkypeGroupDeleted OnGroupDeleted={ read=FOnGroupDeleted, write=FOnGroupDeleted };
  __property TSkypeUserMood OnUserMood={ read=FOnUserMood, write=FOnUserMood };
  __property TSkypeSmsMessageStatusChanged OnSmsMessageStatusChanged={ read=FOnSmsMessageStatusChanged, write=FOnSmsMessageStatusChanged };
  __property TSkypeSmsTargetStatusChanged OnSmsTargetStatusChanged={ read=FOnSmsTargetStatusChanged, write=FOnSmsTargetStatusChanged };
  __property TSkypeCallInputStatusChanged OnCallInputStatusChanged={ read=FOnCallInputStatusChanged, write=FOnCallInputStatusChanged };
  __property TSkypeAsyncSearchUsersFinished OnAsyncSearchUsersFinished={ read=FOnAsyncSearchUsersFinished, write=FOnAsyncSearchUsersFinished };
  __property TSkypeCallSeenStatusChanged OnCallSeenStatusChanged={ read=FOnCallSeenStatusChanged, write=FOnCallSeenStatusChanged };
  __property TSkypePluginEventClicked OnPluginEventClicked={ read=FOnPluginEventClicked, write=FOnPluginEventClicked };
  __property TSkypePluginMenuItemClicked OnPluginMenuItemClicked={ read=FOnPluginMenuItemClicked, write=FOnPluginMenuItemClicked };
  __property TSkypeWallpaperChanged OnWallpaperChanged={ read=FOnWallpaperChanged, write=FOnWallpaperChanged };
  __property TSkypeFileTransferStatusChanged OnFileTransferStatusChanged={ read=FOnFileTransferStatusChanged, write=FOnFileTransferStatusChanged };
  __property TSkypeCallTransferStatusChanged OnCallTransferStatusChanged={ read=FOnCallTransferStatusChanged, write=FOnCallTransferStatusChanged };
  __property TSkypeChatMembersChanged OnChatMembersChanged={ read=FOnChatMembersChanged, write=FOnChatMembersChanged };
  __property TSkypeChatMemberRoleChanged OnChatMemberRoleChanged={ read=FOnChatMemberRoleChanged, write=FOnChatMemberRoleChanged };
  __property TSkypeCallVideoStatusChanged OnCallVideoStatusChanged={ read=FOnCallVideoStatusChanged, write=FOnCallVideoStatusChanged };
  __property TSkypeCallVideoSendStatusChanged OnCallVideoSendStatusChanged={ read=FOnCallVideoSendStatusChanged, write=FOnCallVideoSendStatusChanged };
  __property TSkypeCallVideoReceiveStatusChanged OnCallVideoReceiveStatusChanged={ read=FOnCallVideoReceiveStatusChanged, write=FOnCallVideoReceiveStatusChanged };
  __property TSkypeSilentModeStatusChanged OnSilentModeStatusChanged={ read=FOnSilentModeStatusChanged, write=FOnSilentModeStatusChanged };
  __property TSkypeUILanguageChanged OnUILanguageChanged={ read=FOnUILanguageChanged, write=FOnUILanguageChanged };
  __property TSkypeUserAuthorizationRequestReceived OnUserAuthorizationRequestReceived={ read=FOnUserAuthorizationRequestReceived, write=FOnUserAuthorizationRequestReceived };
};
typedef TSkype  TSkypeProxy;

};     // namespace Skype4comlib_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Skype4comlib_tlb;
#endif

#pragma option pop

#endif // SKYPE4COMLib_OCXH
